Metrics/BlockLength:
  Exclude:
    - Rakefile
    - '.bundle/**/*'
    - 'bin/**/*'
    - 'spec/**/*'
Style/Documentation:
  Enabled: false
Layout/LineLength:
  Exclude:
    - 'spec/spec_helper.rb'
Naming/MethodParameterName:
  Enabled: false
Style/AccessModifierDeclarations:
  EnforcedStyle: 'inline'
Metrics/MethodLength:
  Exclude:
  - 'lib/model/world.rb'
  - 'lib/main_file.rb'
Metrics/CyclomaticComplexity:
  Exclude:
  - 'lib/model/world.rb'
